#!/usr/bin/env node
/**
 * build-content.js — Inline qualify-content-vX.json into the Qualify HTML apps.
 *
 * Both Qualify apps (consulting standalone and website MVP) read their scoring
 * intelligence — questions, rubrics, persona, opp-type calibration, rebid
 * modifier — from a single versioned JSON file in this directory. This script
 * embeds that JSON into each HTML file between sentinel markers so the apps
 * stay single-file (no runtime fetch, no server dependency).
 *
 * Usage:
 *   node pwin-qualify/content/build-content.js                # build with latest version
 *   node pwin-qualify/content/build-content.js --version 0.1  # build a specific version
 *   node pwin-qualify/content/build-content.js --check        # verify both apps are in sync with the latest content
 *
 * The sentinel markers in each HTML file look like this:
 *   // <QUALIFY_CONTENT_BEGIN vX.Y.Z>
 *   const QUALIFY_CONTENT = { ... };
 *   // <QUALIFY_CONTENT_END>
 *
 * Everything between (and including) those markers is replaced. The script
 * leaves the rest of the HTML untouched.
 */

const fs = require('fs');
const path = require('path');

const CONTENT_DIR = __dirname;
const REPO_ROOT = path.resolve(__dirname, '..', '..');

const TARGETS = [
  {
    label: 'consulting standalone',
    path: path.join(REPO_ROOT, 'pwin-qualify', 'docs', 'PWIN_Architect_v1.html'),
  },
  {
    label: 'website MVP',
    path: path.join(REPO_ROOT, 'bidequity-co', 'qualify-app.html'),
  },
];

const BEGIN_RE = /\/\/ <QUALIFY_CONTENT_BEGIN[^>]*>[\s\S]*?\/\/ <QUALIFY_CONTENT_END>/;

function findLatestContentFile() {
  const files = fs.readdirSync(CONTENT_DIR)
    .filter(f => /^qualify-content-v[\d.]+\.json$/.test(f))
    .sort();
  if (files.length === 0) {
    throw new Error('No qualify-content-vX.Y.json file found in ' + CONTENT_DIR);
  }
  return path.join(CONTENT_DIR, files[files.length - 1]);
}

function loadContent(versionArg) {
  let file;
  if (versionArg) {
    file = path.join(CONTENT_DIR, `qualify-content-v${versionArg}.json`);
    if (!fs.existsSync(file)) throw new Error('Not found: ' + file);
  } else {
    file = findLatestContentFile();
  }
  const json = JSON.parse(fs.readFileSync(file, 'utf8'));
  return { file, json };
}

function buildSentinelBlock(content) {
  // Pretty-printed but compact enough that the HTML file stays readable.
  // We embed the literal JSON object so the runtime can use it directly with
  // no JSON.parse overhead and no escaping headaches.
  const literal = JSON.stringify(content, null, 2);
  return [
    `// <QUALIFY_CONTENT_BEGIN v${content.version}>`,
    `// AUTO-GENERATED by pwin-qualify/content/build-content.js — DO NOT EDIT BY HAND.`,
    `// Source: pwin-qualify/content/qualify-content-v${content.version}.json`,
    `// To change scoring/persona/rubric content, edit the JSON and re-run the build.`,
    `const QUALIFY_CONTENT = ${literal};`,
    `// <QUALIFY_CONTENT_END>`,
  ].join('\n');
}

function applyToFile(target, block, content, mode) {
  const html = fs.readFileSync(target.path, 'utf8');
  let updated;

  if (BEGIN_RE.test(html)) {
    updated = html.replace(BEGIN_RE, block);
  } else {
    // First-time install: inject the block immediately before the QUALIFY CONTENT
    // HYDRATION header comment that starts the hydration block in both apps.
    const anchor = /\n(\s*)\/\/ ══════════════════════════════════════════════════════════════\n\1\/\/ QUALIFY CONTENT HYDRATION/;
    if (!anchor.test(html)) {
      throw new Error(`Cannot find injection anchor in ${target.label} (${target.path}). Expected '// QUALIFY CONTENT HYDRATION' header.`);
    }
    updated = html.replace(anchor, `\n$1${block}\n\n$1// ══════════════════════════════════════════════════════════════\n$1// QUALIFY CONTENT HYDRATION`);
  }

  if (mode === 'check') {
    if (updated !== html) {
      console.error(`OUT OF SYNC: ${target.label} (${target.path})`);
      return false;
    }
    console.log(`  in sync: ${target.label}`);
    return true;
  }

  if (updated === html) {
    console.log(`  unchanged: ${target.label}`);
  } else {
    fs.writeFileSync(target.path, updated);
    console.log(`  updated:   ${target.label}`);
  }
  return true;
}

function main() {
  const args = process.argv.slice(2);
  let version = null;
  let mode = 'build';
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--version') version = args[++i];
    else if (args[i] === '--check') mode = 'check';
    else if (args[i] === '--help' || args[i] === '-h') {
      console.log(fs.readFileSync(__filename, 'utf8').split('*/')[0]);
      process.exit(0);
    }
  }

  const { file, json } = loadContent(version);
  console.log(`Source: ${path.relative(REPO_ROOT, file)}`);
  console.log(`Version: ${json.version}  (last updated ${json.lastUpdated})`);
  console.log(`Mode: ${mode}`);
  console.log('');

  const block = buildSentinelBlock(json);

  let allOk = true;
  for (const target of TARGETS) {
    if (!fs.existsSync(target.path)) {
      console.error(`  MISSING: ${target.label} (${target.path})`);
      allOk = false;
      continue;
    }
    const ok = applyToFile(target, block, json, mode);
    if (!ok) allOk = false;
  }

  if (mode === 'check' && !allOk) {
    console.error('\nOne or more apps are out of sync with the latest content. Run without --check to fix.');
    process.exit(1);
  }

  console.log('\nDone.');
}

main();
